### ISSUE TITLE
Function keys support

### ISSUE THREAD

**Issue by chaudharyjatin115** [cutefishos/core#19]
my dell laptop recives the input from media and brightness keys but dosent do anything

**Comment by l0l67** [comment]
https://wiki.archlinux.org/title/Xbindkeys#Audio_control

**Comment by l0l67** [comment]
[Yes](https://manpages.debian.org/bullseye/xbindkeys/xbindkeys.1.en.html)

**Comment by chaudharyjatin115** [comment]
hey thanks it fixed every functionkeys
