### ISSUE TITLE
Please do not force change gtk-3.0 theme

### ISSUE THREAD

**Issue by joe733** [cutefishos/core#33]
`~/.config/gtk-3.0/settings.ini` gets re-written every time with:

```ini
[Settings]
...
gtk-icon-theme-name=Crule
gtk-theme-name=Cutefish-dark
```

**Comment by nisel11** [comment]
I can change the gtk3 theme using the lxapperance app. The steps are as follows: 1. If the user has the theme installed, then install it on the whole system, namely copy the folder with the theme to /usr/share/themes/ . 2. Run lxapperance with sudo rights and select the theme and then apply it. 3. Your theme should already work, but if not, do step 2, but without sudo rights.     I haven't found a way to change icons theme, but you can copy icons of your theme found in /usr/share/icons/name to /usr/share/icons/Crule/ and then they will change, but icons that were not there before on apps will most likely not work, you need to manually change app file in /usr/share/applications/ and change word after Icon= to file name in /usr/share/icons/Crule/apps/scalable/ without . svg and after restarting the icons will change. I also don't recommend running apps that use gtk before changing the gtk theme as you will have to change the theme after every restart, you will have to select a different theme, click apply and then select the desired theme and click apply.

**Comment by nisel11** [comment]
But hopefully soon there will be an update adding 
the ability to change the gtk theme, there's a reason they canceled the fork.

**Comment by nisel11** [comment]
I should tell you right away that maybe what I wrote won't work because I have reinstalled cutefish on arch linux more than once and not always lxapperance was able to change the theme
